[package]
name = "example"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
auto_api = { path = "../auto_api" }

serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0"
